<?php

class MarkupAddInlineScript extends WireData implements Module {

    /**
     * getModuleInfo is a module required by all modules to tell ProcessWire about them
     *
     * @return array
     *
     */
    public static function getModuleInfo() {
        return array(
            'title'    => 'Inline Scripts',
            'version'  => '2.8.1',
            'summary'  => 'adds inline script before </body>',
            'singular' => true,
            'autoload' => true,
            'requires' => 'MarkupLeafletMap',
            'Author'   => 'gebeer',
        );
    }

    /**
     * Initialize the module
     *
     * ProcessWire calls this when the module is loaded. For 'autoload' modules, this will be called
     * when ProcessWire's API is ready. As a result, this is a good place to attach hooks.
     *
     */
    public function init() {
        $this->addHookAfter('Page::render', $this, 'addInlineScript');
    }

    public function addInlineScript($event) {
        $page = $event->object;
        if ($page->template->name !== "admin" && $page->inlineScript) {
            $event->return = str_replace("</body>", $page->inlineScript . "</body>", $event->return);
        }
    }
}
